services:
  - type: web
    name: portfolio-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: UPSTASH_REDIS_URL
        sync: false
      - key: CELERY_TASK_ALWAYS_EAGER
        value: "True"
      - key: FRONTEND_ORIGIN
        value: "*"
      - key: UPLOAD_FOLDER
        value: uploads
